---
- name: Update project name and description
  uri:
    url: "{{ git_url }}/api/v4/projects/{{ project_id }}?name={{ morpheus['customOptions']['updejt_ime'] }}&private_token={{ git_api }}&description={{ project_desc }}"
    method: PUT
    status_code: 200
    body_format: json
  register: result # LIKE THIS WE SAVE OUR RESULT IN VARIABLE = :result:
  no_log: 1 # DOES NOT SHOW RESULTS, HIDDEN

- name: Print  error code
  debug:
    msg="{{ result.status }}"
  when: result.status != 200 
